// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVFZjj7rjdcPOBUWWPAJ8FWsY2XL7KC8',
    appId: '1:170735395486:web:d8814c8e29d12c780fd18f',
    messagingSenderId: '170735395486',
    projectId: 'precise-sight-372314',
    authDomain: 'precise-sight-372314.firebaseapp.com',
    storageBucket: 'precise-sight-372314.appspot.com',
    measurementId: 'G-5YGQSYTF75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSOEz_d1a3mnYmBNFzz2t8tv02HpXBcA0',
    appId: '1:170735395486:android:b416e970326cf3ae0fd18f',
    messagingSenderId: '170735395486',
    projectId: 'precise-sight-372314',
    storageBucket: 'precise-sight-372314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeXmMr_r6xLHreVV_rh0fIjqCfG8N0ziw',
    appId: '1:170735395486:ios:45dd512d36b017720fd18f',
    messagingSenderId: '170735395486',
    projectId: 'precise-sight-372314',
    storageBucket: 'precise-sight-372314.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeXmMr_r6xLHreVV_rh0fIjqCfG8N0ziw',
    appId: '1:170735395486:ios:964be700874ddf540fd18f',
    messagingSenderId: '170735395486',
    projectId: 'precise-sight-372314',
    storageBucket: 'precise-sight-372314.appspot.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
